# Generated by Django 6.0.1 on 2026-01-25 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title/考试名称', max_length=20, verbose_name='考试名称')),
                ('student_number', models.CharField(help_text='student_number/学号', max_length=20, verbose_name='学号')),
                ('student_name', models.CharField(help_text='student_name/姓名', max_length=20, verbose_name='姓名')),
                ('chinese_score', models.DecimalField(decimal_places=2, help_text='chinese_score/语文成绩', max_digits=5, verbose_name='语文成绩')),
                ('math_score', models.DecimalField(decimal_places=2, help_text='math_score/数学成绩', max_digits=5, verbose_name='数学成绩')),
                ('english_score', models.DecimalField(decimal_places=2, help_text='english_score/英语成绩', max_digits=5, verbose_name='英语成绩')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='grades.grade', verbose_name='班级')),
            ],
            options={
                'verbose_name': '成绩信息',
                'verbose_name_plural': '成绩信息',
                'db_table': 'score',
            },
        ),
    ]
