# Generated by Django 6.0.1 on 2026-01-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='学号'),
        ),
    ]
